//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseMarkers = new HashSet<CourseMarker>();
            this.CoursePoints = new HashSet<CoursePoint>();
            this.Laps = new HashSet<Lap>();
            this.Participants = new HashSet<Participant>();
            this.TrackPoints = new HashSet<TrackPoint>();
            this.PointsOfInterests = new HashSet<PointOfInterest>();
        }
    
        public int CourseID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> ElevGain { get; set; }
        public string Description { get; set; }
        public Nullable<int> FK_Event { get; set; }
        public Nullable<int> Order { get; set; }
        public string StrokeColor { get; set; }
        public Nullable<int> StrokeThickness { get; set; }
        public string StrokeDash { get; set; }
    
        public virtual ICollection<CourseMarker> CourseMarkers { get; set; }
        public virtual ICollection<CoursePoint> CoursePoints { get; set; }
        public virtual ICollection<Lap> Laps { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<TrackPoint> TrackPoints { get; set; }
        public virtual ICollection<PointOfInterest> PointsOfInterests { get; set; }
        public virtual Event Event { get; set; }
    }
}
