//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lap
    {
        public int LapID { get; set; }
        public int FK_Participant { get; set; }
        public int FK_Event { get; set; }
        public Nullable<int> RunnerNo { get; set; }
        public int FK_Course { get; set; }
        public Nullable<int> LapNo { get; set; }
        public int Status { get; set; }
        public Nullable<int> TimeElapsed { get; set; }
        public Nullable<int> TimeRemaining { get; set; }
        public Nullable<int> TimeTotal { get; set; }
        public Nullable<double> DistanceTotal { get; set; }
        public Nullable<double> DistanceCompleted { get; set; }
        public Nullable<double> DistanceRemaining { get; set; }
        public Nullable<int> LapPace { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ProjTotalTime { get; set; }
        public Nullable<System.DateTime> ProjStartTime { get; set; }
        public Nullable<System.DateTime> ProjEndTime { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Event Event { get; set; }
    }
}
