//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveTracker
    {
        public int PointID { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Altitude { get; set; }
        public Nullable<double> BatteryPct { get; set; }
        public int TrackerID { get; set; }
        public string ParticipantName { get; set; }
        public Nullable<int> Bib { get; set; }
        public string EventName { get; set; }
        public Nullable<long> rk { get; set; }
    }
}
