//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.Laps = new HashSet<Lap>();
            this.Trackers = new HashSet<Tracker>();
            this.TrackPoints = new HashSet<TrackPoint>();
        }
    
        public int PartID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Bib { get; set; }
        public Nullable<int> Lap { get; set; }
        public Nullable<int> FK_Course { get; set; }
        public Nullable<int> FK_Event { get; set; }
        public Nullable<int> FK_Type { get; set; }
        public Nullable<int> Runners { get; set; }
        public int StartFinishPos { get; set; }
        public Nullable<int> TimeElapsed { get; set; }
        public Nullable<int> TimeRemaining { get; set; }
        public Nullable<int> TimeTotal { get; set; }
        public Nullable<double> DistanceTotal { get; set; }
        public Nullable<double> DistanceCompleted { get; set; }
        public Nullable<double> DistanceRemaining { get; set; }
        public Nullable<int> AvgPace { get; set; }
        public Nullable<int> CurrPace { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TotalPace { get; set; }
        public Nullable<int> CourseNo { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual ICollection<Lap> Laps { get; set; }
        public virtual ParticipantType ParticipantType { get; set; }
        public virtual ICollection<Tracker> Trackers { get; set; }
        public virtual ICollection<TrackPoint> TrackPoints { get; set; }
        public virtual Event Event { get; set; }
    }
}
