//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfInterest
    {
        public int PointID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Location { get; set; }
        public string Icon { get; set; }
        public Nullable<int> FK_Course { get; set; }
        public string InfoBoxText { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
