//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceSeries
    {
        public RaceSeries()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int SeriesID { get; set; }
        public string SeriesName { get; set; }
        public string SeriesType { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
