//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCard
    {
        public SimCard()
        {
            this.Trackers = new HashSet<Tracker>();
        }
    
        public int SimID { get; set; }
        public string SimNo { get; set; }
        public string PhoneNo { get; set; }
        public string Provider { get; set; }
        public string PlanDesc { get; set; }
    
        public virtual ICollection<Tracker> Trackers { get; set; }
    }
}
