//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StrideFlyEntities : DbContext
    {
        public StrideFlyEntities()
            : base("name=StrideFlyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RaceSeries> RaceSeries1 { get; set; }
        public DbSet<SimCard> SimCards { get; set; }
        public DbSet<CourseMarker> CourseMarkers { get; set; }
        public DbSet<ParticipantType> ParticipantTypes { get; set; }
        public DbSet<Tracker> Trackers { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CoursePoint> CoursePoints { get; set; }
        public DbSet<Lap> Laps { get; set; }
        public DbSet<LiveLap> LiveLaps { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<TrackPoint> TrackPoints { get; set; }
        public DbSet<LiveParticipant> LiveParticipants { get; set; }
        public DbSet<LiveTracker> LiveTrackers { get; set; }
        public DbSet<PointOfInterest> PointOfInterests { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<vEvent> vEvents { get; set; }
    }
}
