//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrideFlyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEvent
    {
        public int EventID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<int> TimeDiffPT { get; set; }
        public int SeriesID { get; set; }
        public string Location { get; set; }
        public string SeriesName { get; set; }
        public string SeriesType { get; set; }
        public Nullable<int> Laps { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public Nullable<int> CycleInterval { get; set; }
    }
}
